export enum ServerEvents {
    ConnectedToServer = 'connectedToServer',
	ChangeScore = 'changeScore',
	ChangeState = 'changeState',
	Users = 'users',
	VotingResults = 'votingResults',
	CardForTheDesk = 'cardForTheDesk',
	JoinRoom = 'joinRoom',
	CountOfUsers = 'joinRoom',
	Association = 'association',
	HandCards = 'giveCards',
	OneCard = 'giveOneCard',
	MyCardOnTheDesk = 'myCardOnTheDesk',
	ChooseCardAsAHeader = 'chooseCardAsAHeader',
	ChooseCardAsAUser = 'chooseCardAsAUser',
	VoteForTheCard = 'voteForTheCard',
	MoveToNextRound = 'moveToNextRound',
	LeaveRoom = 'leaveRoom',
	StartGame = 'startGame'
}